### ISSUE TITLE
重名文件问题

### ISSUE THREAD

**Issue by ninthseason** [ninthseason/nonebot-plugin-directlinker#10]
两个文件重名时只会输出一个文件的直链

**Comment by Reversedeer** [comment]
那就不要重名啊，这个不是插件问题，改个名字不就行了

**Comment by SakuraPuare** [comment]
fixed at [✨ feat: 添加文件序号](https://github.com/Utmost-Happiness-Planet/nonebot-plugin-directlinker/commit/19f10b9c77820beb1b0e609981e204f973fdb52f)
