### ISSUE TITLE
[BUG] 无文件夹的群文件

### ISSUE THREAD

**Issue by Peins** [ninthseason/nonebot-plugin-directlinker#11]
![image](https://user-images.githubusercontent.com/44390166/218300954-86ffcd63-e118-41c4-b3db-01193236365c.png)
版本2.3.1

**Comment by SakuraPuare** [comment]
请提供群文件截图

**Comment by SakuraPuare** [comment]
猜测是因为你的群聊中没有文件夹
已经在 [🐞 fix: 无文件夹的群文件](https://github.com/Utmost-Happiness-Planet/nonebot-plugin-directlinker/commit/ed0bd770fe6878390191060cdc7628e0a717d960) 修复，请手动安装插件到 `plugin` 文件夹

或在群文件中创建一个文件夹以解决

**Comment by Peins** [comment]
确实，
![image](https://user-images.githubusercontent.com/44390166/218301424-37741a79-a928-4b04-b49f-310ff19f242e.png)
![image](https://user-images.githubusercontent.com/44390166/218301437-6cfe4de9-477f-40f0-86ce-f25f95799e44.png)

**Comment by Peins** [comment]
> 确实， ![image](https://user-images.githubusercontent.com/44390166/218301424-37741a79-a928-4b04-b49f-310ff19f242e.png) ![image](https://user-images.githubusercontent.com/44390166/218301437-6cfe4de9-477f-40f0-86ce-f25f95799e44.png)

这是上述报错时候的命令和群文件

**Comment by SakuraPuare** [comment]
商店的插件版本未更新，请手动安装本仓库插件
或 在群文件中创建一个文件夹

**Comment by ninthseason** [comment]
pypi已更新
