### ISSUE TITLE
好像适配不完全,link -n a.txt 失败

### ISSUE THREAD

**Issue by buer5ec** [ninthseason/nonebot-plugin-directlinker#2]
![image](https://user-images.githubusercontent.com/60963396/150518068-3c6a5252-f9b9-4621-8772-541763b8d6ab.png)

![image](https://user-images.githubusercontent.com/60963396/150518132-692dd3bb-c4a5-4a95-8843-ad6b6522a617.png)

**Comment by ninthseason** [comment]
恭喜你发现本插件的一个bug，稍后我会修复

**Comment by ninthseason** [comment]
已修复，请重新安装最新版插件（插件版本应为2.1.0，pip清华镜像站有所延时)

**Comment by buer5ec** [comment]
感激不尽




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ninthseason/nonebot-plugin-directlinker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月21日(星期五) 晚上7:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ninthseason/nonebot-plugin-directlinker] 好像适配不完全,link -n a.txt 失败 (Issue #2)





 
已修复，请重新安装最新版插件（插件版本应为2.1.0，pip清华镜像站有所延时)
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
