### ISSUE TITLE
有没有可能把转发的聊天记录里面的文件也提取直链呢？

### ISSUE THREAD

**Issue by Moekey114514** [ninthseason/nonebot-plugin-directlinker#5]
不太懂转发的文件是不是算群文件，有的时候转发消息因为莫名其妙的原因就打不开了，导致里面的文件也看不了，能不能提取转发消息里面文件的直链？

**Comment by ninthseason** [comment]
转发的文件不算是群文件。因为这里的群文件指在保存在**本群** “文件” 目录中的文件。
因为操作逻辑不同，该插件并不支持提取转发消息的文件。且因为个人时间有限，我不太可能继续插件的开发。
深感歉意。🙂
