### ISSUE TITLE
[bug]无法正常使用+pr

### ISSUE THREAD

**Issue by Reversedeer** [ninthseason/nonebot-plugin-directlinker#7]
安装后报错，检查了一下源码，应该是作者的pypi没更新缺少了几行代码，github上的版本最新可以使用,

**Comment by Reversedeer** [comment]
![image](https://user-images.githubusercontent.com/87823528/208087300-4e560973-1862-4a63-8678-01d675b72aee.png)
此部分为缺失的代码

**Comment by ninthseason** [comment]
不小心把pypi的版本号搞混了ಠ_ಠ
现在好了。
最新版本为2.2.2
