### ISSUE TITLE
适配nonebot2.0.0rc1没有加到pypi里

### ISSUE THREAD

**Issue by Agnes4m** [ninthseason/nonebot-plugin-directlinker#8]
![image](https://user-images.githubusercontent.com/70925546/209499912-77888b58-20f0-4801-9be1-2493cd524051.png)

**Comment by ninthseason** [comment]
请使用`pip install nonebot-plugin-directlinker==2.2.2`安装最新版2.2.2版本的插件

之前因操作失误将一个旧版本作为3.0.0版本上传了pypi。现已撤销3.0.0版本，最新版本为2.2.2。
